<a href="https://colab.research.google.com/github/leusam12/Programming-for-data-analysis-CMP7005_S1_25/blob/main/ASSESMENT_FOR_PROGRAMING_FOR_DATA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# load in the dataset
from google.colab import drive

#this will prompt for authorization
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
%cd '/content/drive/MyDrive/program for data analysis'

/content/drive/MyDrive/program for data analysis

In [3]:
%ls

Ahmedabad_data.csv       Chennai_data.csv     Kochi_data.csv
Aizawl_data.csv          Coimbatore_data.csv  Kolkata_data.csv
all_cities_combined.csv  Delhi_data.csv       Lucknow_data.csv
Amaravati_data.csv       Ernakulam_data.csv   Mumbai_data.csv
Amritsar_data.csv        Gurugram_data.csv    Patna_data.csv
Bengaluru_data.csv       Guwahati_data.csv    Shillong_data.csv
Bhopal_data.csv          Hyderabad_data.csv   Talcher_data.csv
Brajrajnagar_data.csv    Jaipur_data.csv      Thiruvananthapuram_data.csv
Chandigarh_data.csv      Jorapokhar_data.csv  Visakhapatnam_data.csv

In [4]:
drive_path ='/content/drive/MyDrive/program for data analysis'

In [5]:
import os
import pandas as pd

dataframes = []
for filename in os.listdir(drive_path):
    if filename.endswith('.csv'):  # Check if the file is a CSV file
        file_path = os.path.join(drive_path, filename)
        df = pd.read_csv(file_path)  # Read the CSV file into a DataFrame
        dataframes.append(df)  # Add the DataFrame to the list

In [6]:
df1 = pd.concat(dataframes, ignore_index=True)

In [7]:
df1

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ernakulam,22/01/2020,37.48,80.65,127.81,7.76,135.57,101.97,1.94,3.34,NaN,0.64,1.01,0.12,NaN,NaN
1,Ernakulam,23/01/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ernakulam,24/01/2020,41.13,68.71,125.76,7.95,133.71,102.66,1.12,3.46,NaN,0.68,1.87,0.31,NaN,NaN
3,Ernakulam,25/01/2020,53.00,84.58,126.22,7.80,134.02,104.05,1.17,3.48,NaN,0.90,1.93,0.19,154.0,Moderate
4,Ernakulam,26/01/2020,58.31,85.47,125.14,7.95,133.09,103.20,1.20,3.54,NaN,1.15,1.83,0.18,153.0,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59057,Talcher,27/06/2020,20.75,25.94,8.17,21.95,15.89,6.73,1.18,18.62,48.87,0.00,NaN,NaN,90.0,Satisfactory
59058,Talcher,28/06/2020,24.88,31.07,NaN,NaN,0.00,NaN,1.55,21.33,48.55,0.00,NaN,NaN,98.0,Satisfactory
59059,Talcher,29/06/2020,20.37,25.46,22.82,19.64,18.96,10.23,1.59,20.79,46.84,0.00,NaN,NaN,99.0,Satisfactory
59060,Talcher,30/06/2020,18.62,23.26,21.24,26.53,47.60,4.45,1.30,14.34,28.77,0.00,NaN,NaN,86.0,Satisfactory
59061,Talcher,01/07/2020,24.85,31.06,27.73,29.36,57.09,1.37,1.52,14.42,14.90,0.00,NaN,NaN,101.0,Moderate

In [8]:
df1.head(10)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ernakulam,22/01/2020,37.48,80.65,127.81,7.76,135.57,101.97,1.94,3.34,NaN,0.64,1.01,0.12,NaN,NaN
1,Ernakulam,23/01/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ernakulam,24/01/2020,41.13,68.71,125.76,7.95,133.71,102.66,1.12,3.46,NaN,0.68,1.87,0.31,NaN,NaN
3,Ernakulam,25/01/2020,53.00,84.58,126.22,7.80,134.02,104.05,1.17,3.48,NaN,0.90,1.93,0.19,154.0,Moderate
4,Ernakulam,26/01/2020,58.31,85.47,125.14,7.95,133.09,103.20,1.20,3.54,NaN,1.15,1.83,0.18,153.0,Moderate
5,Ernakulam,27/01/2020,53.06,80.24,152.12,5.90,156.21,133.25,1.24,3.49,NaN,1.34,2.34,0.20,159.0,Moderate
6,Ernakulam,28/01/2020,60.99,95.07,133.50,7.48,140.31,107.43,1.37,3.64,NaN,1.62,2.50,0.30,180.0,Moderate
7,Ernakulam,29/01/2020,57.41,96.70,67.41,16.13,83.55,36.60,1.35,3.59,NaN,5.05,9.85,1.39,127.0,Moderate
8,Ernakulam,30/01/2020,43.89,79.30,44.57,19.16,63.72,19.41,1.35,3.54,NaN,4.97,6.40,0.94,96.0,Satisfactory
9,Ernakulam,31/01/2020,35.45,78.48,43.56,19.28,62.85,28.95,1.27,3.58,NaN,3.90,5.24,0.73,89.0,Satisfactory

In [9]:
df1.tail(10)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
59052,Talcher,22/06/2020,13.58,16.97,NaN,NaN,0.00,NaN,0.52,16.61,NaN,0.0,NaN,NaN,51.0,Satisfactory
59053,Talcher,23/06/2020,18.24,22.76,NaN,NaN,0.00,NaN,0.59,16.62,NaN,0.0,NaN,NaN,40.0,Good
59054,Talcher,24/06/2020,14.12,17.63,10.62,20.28,6.98,NaN,0.30,17.07,40.03,0.0,NaN,NaN,62.0,Satisfactory
59055,Talcher,25/06/2020,12.02,14.99,7.69,25.50,21.60,4.62,0.46,17.23,44.58,0.0,NaN,NaN,75.0,Satisfactory
59056,Talcher,26/06/2020,13.17,16.46,7.31,21.50,28.81,7.93,0.93,17.52,44.96,0.0,NaN,NaN,79.0,Satisfactory
59057,Talcher,27/06/2020,20.75,25.94,8.17,21.95,15.89,6.73,1.18,18.62,48.87,0.0,NaN,NaN,90.0,Satisfactory
59058,Talcher,28/06/2020,24.88,31.07,NaN,NaN,0.00,NaN,1.55,21.33,48.55,0.0,NaN,NaN,98.0,Satisfactory
59059,Talcher,29/06/2020,20.37,25.46,22.82,19.64,18.96,10.23,1.59,20.79,46.84,0.0,NaN,NaN,99.0,Satisfactory
59060,Talcher,30/06/2020,18.62,23.26,21.24,26.53,47.60,4.45,1.30,14.34,28.77,0.0,NaN,NaN,86.0,Satisfactory
59061,Talcher,01/07/2020,24.85,31.06,27.73,29.36,57.09,1.37,1.52,14.42,14.90,0.0,NaN,NaN,101.0,Moderate

In [10]:
df1.shape

(59062, 16)

In [11]:
df1.size

944992

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59062 entries, 0 to 59061
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        59062 non-null  object
 1   Date        59062 non-null  object
 2   PM2.5       49866 non-null  float64
 3   PM10        36782 non-null  float64
 4   NO          51898 non-null  float64
 5   NO2         51892 non-null  float64
 6   NOx         50692 non-null  float64
 7   NH3         38406 non-null  float64
 8   CO          54944 non-null  float64
 9   SO2         51354 non-null  float64
 10  O3          51018 non-null  float64
 11  Benzene     47816 non-null  float64
 12  Toluene     42980 non-null  float64
 13  Xylene      22844 non-null  float64
 14  AQI         49700 non-null  float64
 15  AQI_Bucket  49700 non-null  object
dtypes: float64(13), object(3)
memory usage: 7.2+ MB

In [13]:
df1.describe()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
count,49866.000000,36782.000000,51898.000000,51892.000000,50692.000000,38406.000000,54944.000000,51354.000000,51018.000000,47816.000000,42980.000000,22844.000000,49700.000000
mean,67.450578,118.127103,17.574730,28.560659,32.309123,23.483476,2.248598,14.531977,34.491430,3.280840,8.700972,3.070128,166.463581
std,64.660801,90.603878,22.785627,24.474510,31.645699,25.683941,6.962821,18.133598,21.694716,15.810971,19.968931,6.323109,140.695170
min,0.040000,0.010000,0.020000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000
25%,28.820000,56.252500,5.630000,11.750000,12.820000,8.580000,0.510000,5.670000,18.860000,0.120000,0.600000,0.140000,81.000000
50%,48.570000,95.680000,9.890000,21.690000,23.520000,15.850000,0.890000,9.160000,30.840000,1.070000,2.970000,0.980000,118.000000
75%,80.590000,149.747500,19.950000,37.620000,40.130000,30.020000,1.450000,15.220000,45.570000,3.080000,9.150000,3.350000,208.000000
max,949.990000,1000.000000,390.680000,362.210000,467.630000,352.890000,175.810000,193.860000,257.730000,455.030000,454.850000,170.370000,2049.000000

In [14]:
df1.dtypes

City           object
Date           object
PM2.5         float64
PM10          float64
NO            float64
NO2           float64
NOx           float64
NH3           float64
CO            float64
SO2           float64
O3            float64
Benzene       float64
Toluene       float64
Xylene        float64
AQI           float64
AQI_Bucket     object
dtype: object

In [15]:
df1.columns

Index(['City', 'Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2',
       'O3', 'Benzene', 'Toluene', 'Xylene', 'AQI', 'AQI_Bucket'],
      dtype='object')